sudo: required
services:
  - docker

before_install:
  - docker build -t paulbygrave/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true paulbygrave/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-099887765292"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
    secure: "$AWS_SECRET_KEY"
