sudo: required
services:
  - docker

before_install:
  - docker build -t paulbygrave/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true paulbygrave/docker-react npm run test -- --coverage
